version: '3'

services:
  proxy:
    image: nginx:1.11
    ports:
      - '80:80'
    volumes:
      - ./nginx.develop.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build: 
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./php:/var/www/html/php
    restart: always
  db:
    image: 'mysql:latest'
    volumes: 
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    restart: always
    ports:
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
